name: smoke-install

on:
  workflow_dispatch:

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fresh npm install test
        shell: bash
        run: |
          mkdir smoke
          cd smoke
          npm init -y
          npm install @enqoding/node-red-contrib-quantum@1.0.0-quantum-sec.2